### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Pandoks** [Pandoks/startup-template#1]
# Overview

Handle _authentication_ and _authorization_ for the system in an extensible way.

# TODO

- [ ] Get rid of Lucia Auth and roll completely from scratch
- [ ] Get rid of Oslo and use Oslojs

# Features

## Login

- [x] Login with username/email + password
- [x] Login with username/email + passkey
- [x] 2FA TOTP
- [x] Forgot password reset

## Signup

- [x] Signup with username + email + password
- [x] Signup with username + email + passkey

## 2 Factor Authentication

- [x] Setup 2 factor authentication with app
- [x] Verify 2 factor authentication with TOTP
- [x] 2 factor recovery

## Login Throttling/Rate Limiting

- [x] Login throttle
- [x] Signup throttle
- [x] Limit sensitive endpoint attempts

## Profile

- [ ] Profile page for user
- [ ] Change profile picture
- [ ] Change username
- [ ] CRUD email
- [ ] Change password
- [ ] CRUD passkeys
- [ ] CRUD 2 factor authentication
- [ ] Popup/Sidebar/Individual page for profile

## Test

- [x] #10
- [x] #15
